apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
- namespaces.yaml
- https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
- webserver.yaml
