apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-mediation
  name: demo-mediation
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8290
  selector:
    app: demo-mediation
