openapi: 3.0.1
info:
  title: HelloWorldEndpoint
  description: API Definition of HelloWorldEndpoint
  version: 1.0.0
servers:
- url: http://localhost:8290/hello
paths:
  /:
    get:
      responses:
        default:
          description: Default response
